#ifndef DATATYPEDEFINITIONS_H
#define DATATYPEDEFINITIONS_H

// Estimation Constants
#define DATATYPEDEFINITIONS_CONSTANTSARRAYSIZE ((ULONG) 30)
#define DATATYPEDEFINITIONS_LATITUDEPOINTEXPANSION_INDEX ((ULONG) 0)
#define DATATYPEDEFINITIONS_LONGITUDEPOINTEXPANSION_INDEX ((ULONG) 1)
#define DATATYPEDEFINITIONS_HEIGHTPOINTEXPANSION_INDEX ((ULONG) 2)
#define DATATYPEDEFINITIONS_TIMESHIFTPOINTEXPANSION_INDEX ((ULONG) 3)
#define DATATYPEDEFINITIONS_CLOCKDRIFTPOINTEXPANSION_INDEX ((ULONG) 4)
#define DATATYPEDEFINITIONS_APRIORIVARIANCE_INDEX ((ULONG) 5)
#define DATATYPEDEFINITIONS_VELXECEFPOINTEXPANSION_INDEX ((ULONG) 6)
#define DATATYPEDEFINITIONS_VELYECEFPOINTEXPANSION_INDEX ((ULONG) 7)
#define DATATYPEDEFINITIONS_VELZECEFPOINTEXPANSION_INDEX ((ULONG) 8)
#define DATATYPEDEFINITIONS_PRWXSPECTRALDENSITY_INDEX ((ULONG) 9)
#define DATATYPEDEFINITIONS_PRWYSPECTRALDENSITY_INDEX ((ULONG) 10)
#define DATATYPEDEFINITIONS_PRWZSPECTRALDENSITY_INDEX ((ULONG) 11)
#define DATATYPEDEFINITIONS_PRWCLKBIASSPECTRALDENSITY_INDEX ((ULONG) 12)
#define DATATYPEDEFINITIONS_VRWXSPECTRALDENSITY_INDEX ((ULONG) 13)
#define DATATYPEDEFINITIONS_VRWYSPECTRALDENSITY_INDEX ((ULONG) 14)
#define DATATYPEDEFINITIONS_VRWZSPECTRALDENSITY_INDEX ((ULONG) 15)
#define DATATYPEDEFINITIONS_VRWCLKDRIFTSPECTRALDENSITY_INDEX ((ULONG) 16)
#define DATATYPEDEFINITIONS_CORRVXTIMECONSTANT_INDEX ((ULONG) 17)
#define DATATYPEDEFINITIONS_CORRVYTIMECONSTANT_INDEX ((ULONG) 18)
#define DATATYPEDEFINITIONS_CORRVZTIMECONSTANT_INDEX ((ULONG) 19)
#define DATATYPEDEFINITIONS_CORRCLKDRIFTTIMECONSTANT_INDEX ((ULONG) 20)
#define DATATYPEDEFINITIONS_INITVARX_INDEX ((ULONG) 21)
#define DATATYPEDEFINITIONS_INITVARY_INDEX ((ULONG) 22)
#define DATATYPEDEFINITIONS_INITVARZ_INDEX ((ULONG) 23)
#define DATATYPEDEFINITIONS_INITVARVELX_INDEX ((ULONG) 24)
#define DATATYPEDEFINITIONS_INITVARVELY_INDEX ((ULONG) 25)
#define DATATYPEDEFINITIONS_INITVARVELZ_INDEX ((ULONG) 26)
#define DATATYPEDEFINITIONS_INITVARCLKBIAS_INDEX ((ULONG) 27)
#define DATATYPEDEFINITIONS_INITVARCLKDRIFT_INDEX ((ULONG) 28)
#define DATATYPEDEFINITIONS_IEKFENABLE_INDEX ((ULONG) 29)

// Data type definitions
typedef double DOUBLE;
typedef float FLOAT;
typedef int INT;
typedef unsigned int UINT;
typedef unsigned long ULONG;
typedef unsigned long long ULONGLONG;
typedef long LONG;
typedef long long LONGLONG;
typedef short SHORT;
typedef unsigned short USHORT;
typedef unsigned char UCHAR;
typedef char CHAR;
typedef bool BOOLEANO;

// Constant definitions
// Speed of light in vacuum, m/s
#define SPEED_OF_LIGHT ((DOUBLE) 299792458.0)
#define DATATYPEDEFINITIONS_PI ((DOUBLE) 3.14159265358979323846)
#ifndef TRUE
#define TRUE true
#endif
#ifndef FALSE
#define FALSE false
#endif
#define DATATYPEDEFINITIONS_GPSL1_FREQUENCY ((DOUBLE) 1575.42e6)
#define DATATYPEDEFINITIONS_GPSL2_FREQUENCY ((DOUBLE) 1227.60e6)
#define DATATYPEDEFINITIONS_NUMSTATES ((ULONG) 4)
#define DATATYPEDEFINITIONS_NUMPRN ((ULONG) 32)
#define DATATYPEDEFINITIONS_NUMCHANNELS ((ULONG) 12)

typedef struct SatelliteData
{
   // GNSS Time
   DOUBLE dGNSSTime;
   // Satellite PRN
   ULONG  ulPRN;
   // Satellite PRN X-coordinate ECEF
   DOUBLE dPRNX;
   // Satellite PRN Y-coordinate ECEF
   DOUBLE dPRNY;
   // Satellite PRN Z-coordinate ECEF
   DOUBLE dPRNZ;
   // Pseudorange from antenna to satellite PRN
   DOUBLE dPSR;
   // Carrier phase measurement
   DOUBLE dADR;
   // Satellite PRN elevation angle
   DOUBLE dElevation;
} SatelliteData;

typedef struct TruthData
{
   // GNSS Time
   DOUBLE dGNSSTime;
   // Receiver X-coordinate ECEF
   DOUBLE dXCoord;
   // Receiver Y-coordinate ECEF
   DOUBLE dYCoord;
   // Receiver Z-coordinate ECEF
   DOUBLE dZCoord;
} TruthData;

#endif